server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  location /rule-api/ { proxy_pass http://rule-service:5000/; proxy_set_header Host $host; }
  location /pricing-api/ { proxy_pass http://pricing-service:80/; proxy_set_header Host $host; }
  location / { try_files $uri $uri/ /index.html; }
}
